//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4_Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("4-Recursos.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo não pode ser nulo ou vazio..
        /// </summary>
        public static string CampoNuloOuVazio {
            get {
                return ResourceManager.GetString("CampoNuloOuVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome não pode conter caractere especial..
        /// </summary>
        public static string CaractereEspecialNome {
            get {
                return ResourceManager.GetString("CaractereEspecialNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP não pode ser nulo ou vazio..
        /// </summary>
        public static string CepNuloOuVazio {
            get {
                return ResourceManager.GetString("CepNuloOuVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente possui cadastro..
        /// </summary>
        public static string ClienteExiste {
            get {
                return ResourceManager.GetString("ClienteExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não encontrado..
        /// </summary>
        public static string ClienteNaoEncontrado {
            get {
                return ResourceManager.GetString("ClienteNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro da conta {0} criado com sucesso..
        /// </summary>
        public static string ContaCadastrada {
            get {
                return ResourceManager.GetString("ContaCadastrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta existente..
        /// </summary>
        public static string ContaExistente {
            get {
                return ResourceManager.GetString("ContaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta não encontrada..
        /// </summary>
        public static string ContaNaoEncontrada {
            get {
                return ResourceManager.GetString("ContaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpf não pode ser nulo..
        /// </summary>
        public static string CpfNulo {
            get {
                return ResourceManager.GetString("CpfNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data informada não pode ser maior que a data atual..
        /// </summary>
        public static string DataMaiorQueAtual {
            get {
                return ResourceManager.GetString("DataMaiorQueAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento não pode ser nula ou vazia..
        /// </summary>
        public static string DataNascimentoNulaOuVazia {
            get {
                return ResourceManager.GetString("DataNascimentoNulaOuVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depósito realizado..
        /// </summary>
        public static string DepositoRealizado {
            get {
                return ResourceManager.GetString("DepositoRealizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc realizado..
        /// </summary>
        public static string DocRealizado {
            get {
                return ResourceManager.GetString("DocRealizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado no formato incorreto..
        /// </summary>
        public static string EstadoInvalido {
            get {
                return ResourceManager.GetString("EstadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agência no formato incorreto..
        /// </summary>
        public static string FormatoAgencia {
            get {
                return ResourceManager.GetString("FormatoAgencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP no formato incorreto..
        /// </summary>
        public static string FormatoCep {
            get {
                return ResourceManager.GetString("FormatoCep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF no formato incorreto..
        /// </summary>
        public static string FormatoCpf {
            get {
                return ResourceManager.GetString("FormatoCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento no formato inválido..
        /// </summary>
        public static string FormatoDataNascimento {
            get {
                return ResourceManager.GetString("FormatoDataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de conta no formato inválido..
        /// </summary>
        public static string FormatoNumeroConta {
            get {
                return ResourceManager.GetString("FormatoNumeroConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone no formato inválido..
        /// </summary>
        public static string FormatoTelefone {
            get {
                return ResourceManager.GetString("FormatoTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro não pode ser nulo ou vazio..
        /// </summary>
        public static string LogradouroNuloOuVazio {
            get {
                return ResourceManager.GetString("LogradouroNuloOuVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menor de 18 anos..
        /// </summary>
        public static string MenorDeIdade {
            get {
                return ResourceManager.GetString("MenorDeIdade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome não pode ser nulo ou vazio..
        /// </summary>
        public static string NomeNuloOuVazio {
            get {
                return ResourceManager.GetString("NomeNuloOuVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pix realizado..
        /// </summary>
        public static string PixRealizado {
            get {
                return ResourceManager.GetString("PixRealizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hífen na posição inválida..
        /// </summary>
        public static string PosicaoHifen {
            get {
                return ResourceManager.GetString("PosicaoHifen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto na posição inválida..
        /// </summary>
        public static string PosicaoPonto {
            get {
                return ResourceManager.GetString("PosicaoPonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A primeira letra do nome deve ser maiúscula..
        /// </summary>
        public static string PrimeiraLetraMaiuscula {
            get {
                return ResourceManager.GetString("PrimeiraLetraMaiuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de caracteres diferente de 14..
        /// </summary>
        public static string QtdeCaracteresDifCpf {
            get {
                return ResourceManager.GetString("QtdeCaracteresDifCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de caracteres diferente de 10..
        /// </summary>
        public static string QtdeCaracteresDifNome {
            get {
                return ResourceManager.GetString("QtdeCaracteresDifNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF deve ter 11 números..
        /// </summary>
        public static string QtdeNumerosCpf {
            get {
                return ResourceManager.GetString("QtdeNumerosCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente removido com sucesso..
        /// </summary>
        public static string RemoverCliente {
            get {
                return ResourceManager.GetString("RemoverCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente possui conta e não deve ser deletado..
        /// </summary>
        public static string RemoverClienteComConta {
            get {
                return ResourceManager.GetString("RemoverClienteComConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta removida com sucesso..
        /// </summary>
        public static string RemoverConta {
            get {
                return ResourceManager.GetString("RemoverConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saque realizado..
        /// </summary>
        public static string SaqueRealizado {
            get {
                return ResourceManager.GetString("SaqueRealizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ted realizado..
        /// </summary>
        public static string TedRealizado {
            get {
                return ResourceManager.GetString("TedRealizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de transação inválida..
        /// </summary>
        public static string TransacaoInvalida {
            get {
                return ResourceManager.GetString("TransacaoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação não encontrada..
        /// </summary>
        public static string TransacaoNaoEncontrada {
            get {
                return ResourceManager.GetString("TransacaoNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É permitido somente valores maiores que zero..
        /// </summary>
        public static string ValorMaiorQueZero {
            get {
                return ResourceManager.GetString("ValorMaiorQueZero", resourceCulture);
            }
        }
    }
}
