//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4_Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("4-Recursos.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cliente não foi encontrado..
        /// </summary>
        public static string ClienteNaoEncontrado {
            get {
                return ResourceManager.GetString("ClienteNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro da conta {0} criado com sucesso..
        /// </summary>
        public static string ContaCadastrada {
            get {
                return ResourceManager.GetString("ContaCadastrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta existente..
        /// </summary>
        public static string ContaExistente {
            get {
                return ResourceManager.GetString("ContaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta não foi encontrada..
        /// </summary>
        public static string ContaNaoEncontrada {
            get {
                return ResourceManager.GetString("ContaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados atualizados com sucesso, novo número da conta {0}..
        /// </summary>
        public static string DadosAtualizados {
            get {
                return ResourceManager.GetString("DadosAtualizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi depositado R$ {0}..
        /// </summary>
        public static string Deposito {
            get {
                return ResourceManager.GetString("Deposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados lidos com sucesso, conta {0}..
        /// </summary>
        public static string LeituraDeDados {
            get {
                return ResourceManager.GetString("LeituraDeDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente removido com sucesso..
        /// </summary>
        public static string RemoverCliente {
            get {
                return ResourceManager.GetString("RemoverCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta removida com sucesso..
        /// </summary>
        public static string RemoverConta {
            get {
                return ResourceManager.GetString("RemoverConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saque realizado no valor de R$ {0}..
        /// </summary>
        public static string Saque {
            get {
                return ResourceManager.GetString("Saque", resourceCulture);
            }
        }
    }
}
